### ISSUE TITLE
Tag v1?

### ISSUE THREAD

**Issue by tersmitten** [CakeDC/cakephp-cached-routing#1]
Dear @steinkel,

Long time no see.

My collegue was confused by the lack of any tags in this project. Am I correct that the current `HEAD` (`1.next-cake4`) is version 1? If so, can you do me a favour and tag it?

Regards, Mischa

**Comment by tersmitten** [comment]
And also make sure that it's available on packagist

**Comment by tersmitten** [comment]
Thanks in advance

**Comment by steinkel** [comment]
https://github.com/CakeDC/cakephp-cached-routing/releases/tag/1.0.0 just released, thanks

**Comment by notpron** [comment]
Thanks both 👯

**Comment by tersmitten** [comment]
I'm not able to find it on packagist. Should it (already) be present?

**Comment by tersmitten** [comment]
Nevermind, found it :-)

**Comment by tersmitten** [comment]
https://packagist.org/packages/cakedc/cakephp-cached-routing

**Comment by notpron** [comment]
The composer.json still has `"cakephp/cakephp": "4.next-dev"` as a requirement, can you update that?

**Comment by steinkel** [comment]
updated to ^4.4
